#!/bin/bash

echo "=== DOCKER ROBOT CONTROL SETUP ==="
echo ""
echo "PRIMERO: Compilar el proyecto"
echo "   colcon build"
echo "   source install/setup.bash"
echo ""
echo "=== OPCIÓN 1: TELEOP SIMPLE (RECOMENDADO PARA DOCKER) ==="
echo "1. LANZAR GAZEBO (terminal 1):"
echo "   ros2 launch autonomous_robot_gazebo rosmaster_x3_docker.launch.py"
echo ""
echo "2. ESPERAR A QUE APAREZCA EL ROBOT EN GAZEBO (unos 10 segundos)"
echo ""
echo "3. LANZAR TELEOP SIMPLE (terminal 2):"
echo "   ros2 run autonomous_robot_bringup simple_teleop"
echo ""
echo "   Controles: W=adelante, S=atrás, A=izquierda, D=derecha, SPACE=parar, Q=salir"
echo ""
echo "=== OPCIÓN 2: TELEOP ESTÁNDAR (puede fallar en Docker) ==="
echo "1. LANZAR GAZEBO (terminal 1):"
echo "   ros2 launch autonomous_robot_gazebo rosmaster_x3_docker.launch.py"
echo ""
echo "2. LANZAR TELEOP ESTÁNDAR (terminal 2):"
echo "   ros2 run teleop_twist_keyboard teleop_twist_keyboard"
echo ""
echo "=== VERIFICACIONES (terminal 3) ==="
echo "   # Ver controladores cargados:"
echo "   ros2 control list_controllers"
echo ""
echo "   # Ver comandos del teclado:"
echo "   ros2 topic echo /cmd_vel"
echo ""
echo "   # Ver comandos al controlador:"
echo "   ros2 topic echo /mecanum_drive_controller/cmd_vel"
echo ""
echo "   # Ver todos los tópicos:"
echo "   ros2 topic list"
echo ""
echo "=== CONTROLES TELEOP ESTÁNDAR ==="
echo "Moving around:"
echo "   u    i    o"
echo "   j    k    l"
echo "   m    ,    ."
echo ""
echo "q/z : increase/decrease max speeds by 10%"
echo "w/x : increase/decrease only linear speed by 10%"
echo "e/c : increase/decrease only angular speed by 10%"
echo "space key, k : force stop"
echo "anything else : stop smoothly"
echo ""
echo "CTRL-C to quit"