#!/bin/bash
# Comandos para controlar el robot con teclado en Gazebo

echo "=== COMANDOS PARA CONTROL POR TECLADO DEL ROBOT EN GAZEBO ==="
echo ""
echo "1. OPCIÓN RECOMENDADA (archivo simplificado):"
echo "   ros2 launch autonomous_robot_gazebo rosmaster_x3_simple.launch.py"
echo ""
echo "2. OPCIÓN ORIGINAL (corregida):"
echo "   ros2 launch autonomous_robot_gazebo rosmaster_x3_teleop.launch.py"
echo ""
echo "3. OPCIÓN MANUAL (abrir teleop en terminal separado):"
echo "   Terminal 1: ros2 launch autonomous_robot_gazebo rosmaster_x3_gazebo_only.launch.py"
echo "   Terminal 2: ros2 run teleop_twist_keyboard teleop_twist_keyboard"
echo ""
echo "4. VERIFICAR QUE EL ROBOT ESTÁ RECIBIENDO COMANDOS:"
echo "   ros2 topic echo /cmd_vel"
echo ""
echo "5. VERIFICAR EL CONTROLADOR:"
echo "   ros2 topic echo /mecanum_drive_controller/cmd_vel"
echo ""
echo "6. LISTAR CONTROLADORES ACTIVOS:"
echo "   ros2 control list_controllers"
echo ""
echo "7. DEBUG - Ver todos los tópicos activos:"
echo "   ros2 topic list"
echo ""
echo "=== CONTROLES DE TECLADO ==="
echo "Moving around:"
echo "   u    i    o"
echo "   j    k    l"
echo "   m    ,    ."
echo ""
echo "q/z : increase/decrease max speeds by 10%"
echo "w/x : increase/decrease only linear speed by 10%"
echo "e/c : increase/decrease only angular speed by 10%"
echo "space key, k : force stop"
echo "anything else : stop smoothly"
echo ""
echo "CTRL-C to quit"