<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="inertial_macros.xacro"/>

    <!-- Dimensiones del chasis -->
    <xacro:property name="chassis_length"  value="0.320"/>
    <xacro:property name="chassis_width"   value="0.240"/>
    <xacro:property name="chassis_height"  value="0.078"/>
    <xacro:property name="chassis_mass"    value="0.700"/>

    <!-- Ruedas -->
    <xacro:property name="wheel_radius"    value="0.034"/>
    <xacro:property name="wheel_thickness" value="0.026"/>
    <xacro:property name="wheel_mass"      value="0.050"/>

    <!-- Geometría: vía y altura de rueda (se mantiene la que traías) -->
    <xacro:property name="wheel_offset_y"  value="0.133"/>  <!-- mitad del ancho de vía -->
    <xacro:property name="wheel_offset_z"  value="0.020"/>

    <!-- Nueva distancia entre ejes (Ackermann) -->
    <xacro:property name="wheelbase"       value="${chassis_length}"/><!-- eje trasero en x=0, eje delantero en x=0.20 -->

    <!-- Materiales -->
    <material name="white"><color rgba="1 1 1 1"/></material>
    <material name="black"><color rgba="0 0 0 1"/></material>
    <material name="orange"><color rgba="1 0.25 0 1"/></material>
    <material name="cyan"><color rgba="0 1 1 1"/></material>
    <material name="indigo"><color rgba="0.294 0 0.51 1"/></material>

    <!-- base_link y base_footprint -->
    <link name="base_link"/>
    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>
    <link name="base_footprint"/>

    <!-- Chasis (coincide con tu convención de nombre 'chasis') -->
    <!-- Lo ubicamos igual que antes: su centro queda en (chassis_length/2, 0, chassis_height/2) -->
    <joint name="chasis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chasis"/>
        <origin xyz="0 0 ${-wheel_offset_z}"/>
    </joint>


    <link name="chasis">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${chassis_mass}"
                            x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chasis">
        <material>Gazebo/Black</material>
    </gazebo>

    <!-- ======================= EJE TRASERO (x = 0) ======================= -->

    <joint name="rear_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child  link="rear_left_wheel"/>
        <origin xyz="0 ${wheel_offset_y} 0" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="rear_left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <geometry><sphere radius="${wheel_radius}"/></geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}"
                                 radius="${wheel_radius}" length="${wheel_thickness}">
            <origin xyz="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="rear_left_wheel">
        <material>Gazebo/Orange</material>
    </gazebo>

    <joint name="rear_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child  link="rear_right_wheel"/>
        <origin xyz="0 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="rear_right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <geometry><sphere radius="${wheel_radius}"/></geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}"
                                 radius="${wheel_radius}" length="${wheel_thickness}">
            <origin xyz="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="rear_right_wheel">
        <material>Gazebo/Orange</material>
    </gazebo>

    <!-- ======================= EJE DELANTERO (x = wheelbase) ======================= -->
    <!-- Articulación de dirección (mangueta) izquierda -->
    <joint name="front_left_steer_joint" type="revolute">
        <parent link="base_link"/>
        <child  link="front_left_steer"/>
        <origin xyz="${wheelbase} ${wheel_offset_y} 0"/>
        <axis xyz="0 0 1"/>
        <limit effort="5.0" velocity="2.0" lower="-0.6" upper="0.6"/>
    </joint>

    <link name="front_left_steer">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry><sphere radius="0.01"/></geometry>
            <material name="cyan"/>
        </visual>
        <collision><geometry><sphere radius="0.01"/></geometry></collision>
        <xacro:inertial_sphere mass="0.01" radius="0.01">
            <origin xyz="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <!-- Rueda delantera izquierda bajo la mangueta -->
    <joint name="front_left_wheel_joint" type="continuous">
        <parent link="front_left_steer"/>
        <child  link="front_left_wheel"/>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="front_left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <geometry><sphere radius="${wheel_radius}"/></geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}"
                                 radius="${wheel_radius}" length="${wheel_thickness}">
            <origin xyz="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="front_left_wheel">
        <material>Gazebo/Orange</material>
    </gazebo>

    <!-- Articulación de dirección (mangueta) derecha -->
    <joint name="front_right_steer_joint" type="revolute">
        <parent link="base_link"/>
        <child  link="front_right_steer"/>
        <origin xyz="${wheelbase} ${-wheel_offset_y} 0"/>
        <axis xyz="0 0 1"/>
        <limit effort="5.0" velocity="2.0" lower="-0.6" upper="0.6"/>
    </joint>

    <link name="front_right_steer">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry><sphere radius="0.01"/></geometry>
            <material name="cyan"/>
        </visual>
        <collision><geometry><sphere radius="0.01"/></geometry></collision>
        <xacro:inertial_sphere mass="0.01" radius="0.01">
            <origin xyz="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <!-- Rueda delantera derecha bajo la mangueta -->
    <joint name="front_right_wheel_joint" type="continuous">
        <parent link="front_right_steer"/>
        <child  link="front_right_wheel"/>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="front_right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <geometry><sphere radius="${wheel_radius}"/></geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}"
                                 radius="${wheel_radius}" length="${wheel_thickness}">
            <origin xyz="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="front_right_wheel">
        <material>Gazebo/Orange</material>
    </gazebo>

</robot>
